someVariable = loooooooooooooooooooooooooooooooooooongVariable+
	shortVariable;

someVariable = loooooooooooooooooooooooooooooooooooongVariable+
	anoooooooooooooooooooooooooooooooooooootherVariable+
	shortVariable;

